BEGIN TRANSACTION;
CREATE TABLE items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            author TEXT,
            type TEXT,
            category TEXT,
            summary TEXT,
            link TEXT,
            doi TEXT,
            isbn TEXT,
            journal TEXT,
            year TEXT,
            tags TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
INSERT INTO "items" VALUES(5,'The Colonial Origins of Comparative Development: An Empirical Investigation','Daron Acemoglu, Simon Johnson, James A. Robinson','Paper','Development Economics, Econometrics, Applied Economics','Synopsis
The paper argues that differences in institutions established during colonialism—specifically, whether colonisers created extractive institutions for resource exploitation or inclusive institutions for settlement—are the primary determinant of long-run differences in economic development across countries. Using settler mortality rates as an instrumental variable, the authors demonstrate that colonies with high mortality rates developed extractive institutions and remain poor today.','https://www.jstor.org/stable/2677930','',NULL,NULL,NULL,'#institutions #aer','2026-05-26 08:51:52');
INSERT INTO "items" VALUES(6,'The Use of Knowledge in Society','F A Hayek','Paper','Political Economy, Microeconomics','Hayek argues that centrally planned economies cannot efficiently allocate resources because no single authority can possess all the dispersed knowledge held by individuals throughout society. He contends that prices in free markets serve as a communication mechanism that efficiently transmits this knowledge, allowing decentralized decision-making to produce superior outcomes compared to top-down economic planning.','https://www.jstor.org/stable/1809376','',NULL,NULL,NULL,'#hayek #prices #aer','2026-05-26 10:27:04');
INSERT INTO "items" VALUES(7,'The Market for "Lemons": Quality Uncertainty and the Market Mechanism','George A. Akerlof','Paper','Microeconomics, Applied Economics','George Akerlof demonstrates how information asymmetry between buyers and sellers causes markets to fail when buyers cannot distinguish product quality, leading to a "lemons problem" where only low-quality goods remain in the market as high-quality sellers exit. His analysis explains how uncertainty about quality can unravel entire markets and justifies the existence of warranties, brand names,','https://www.jstor.org/stable/1879431','https://doi.org/10.2307/1879431',NULL,NULL,NULL,'#price #qje','2026-05-26 10:28:17');
INSERT INTO "items" VALUES(8,'The Nature of the Firm','R. H. Coase','Paper','Political Economy, Microeconomics','Coase explains why firms exist by arguing that the transaction costs of coordinating economic activity through market mechanisms make internal organization more efficient in certain contexts. He defines the firm as an alternative to the market where an entrepreneur replaces price signals with direct coordination to reduce the costs of negotiating and enforcing contracts.','https://www.jstor.org/stable/2626876','https://doi.org/10.2307/2626876',NULL,NULL,NULL,'#prices #firms #economica','2026-05-26 10:31:10');
INSERT INTO "items" VALUES(9,'Scaffolding A Novel','Lauren Elkin ','Book','Philosophy, Psychology','Summary unavailable — please add manually.','https://www.google.co.in/books/edition/Scaffolding/lvb8EAAAQBAJ?hl=en&kptab=overview','',NULL,NULL,NULL,'#lacan #psychoanalysis','2026-05-26 10:36:43');
INSERT INTO "items" VALUES(10,'Traditional Institutions Meet the Modern World: Caste, Gender, and Schooling Choice in a Globalizing Economy','Kaivan Munshi, Mark Rosenzweig','Paper','Development Economics, Applied Economics','Summary unavailable — please add manually.','https://www.jstor.org/stable/30034337','10.1257/aer.96.4.1225',NULL,NULL,NULL,'#networks #aer','2026-05-26 10:48:08');
INSERT INTO "items" VALUES(11,'Caste and the Indian Economy','Kaivan Munshi','Paper','','Summary unavailable — please add manually.','https://www.jstor.org/stable/26856206','10.1257/jel.20171307',NULL,NULL,NULL,'#caste #network #jel','2026-05-26 10:51:00');
INSERT INTO "items" VALUES(12,'A Culture of Growth: The Origins of the Modern Economy','Joel Mokyr','Book','Development Economics, Economic History','Mokyr argues that the modern economy originated from a cultural shift in northwestern Europe during the Enlightenment, where new attitudes toward knowledge, innovation, and empiricism replaced traditional thinking and enabled sustained technological progress. He contends that this "culture of growth"—characterized by curiosity, tolerance for new ideas, and the belief that problems could be solved through reason—','https://press.princeton.edu/books/ebook/9780691292496/a-culture-of-growth','',NULL,NULL,NULL,'#growth #technology','2026-05-26 10:59:27');
INSERT INTO "items" VALUES(13,'The Road to Serfdom','F A Hayek','Book','Political Economy, Sociology','Hayek argues that central economic planning and government control, regardless of good intentions, inevitably lead to totalitarianism and the loss of individual freedom. He contends that free markets and the rule of law are essential safeguards against the concentration of power that destroys liberty.','https://press.uchicago.edu/ucp/books/book/chicago/R/bo4138549.html','',NULL,NULL,NULL,'#hayek #polity #liberalism','2026-05-26 11:04:06');
INSERT INTO "items" VALUES(14,'Deep Learning for Solving Economic Models','Jesús Fernández-Villaverde','Paper','Econometrics, Macroeconomics, Microeconomics','Jesús Fernández-Villaverde emphasises that deep learning is revolutionising quantitative economics by enabling the solution of dynamic models traditionally hindered by the curse of dimensionality. Neural networks efficiently approximate equilibrium conditions, offering scalable global solutions. Applied to the neoclassical growth model, this approach expands the methodological frontier of computational economic analysis.','https://www.nber.org/system/files/working_papers/w34250/w34250.pdf','https://doi.org/10.3386/w34250',NULL,NULL,NULL,'#deeplearning #simulations','2026-05-26 17:59:01');
INSERT INTO "items" VALUES(15,'Housing and Inequality','Yannis M. Ioannides, L. Rachel Ngai','Paper','Political Economy, Urban & Spatial Economics','Yannis M. Ioannides and L. Rachel Ngai examine housing as both a driver and a reflection of inequality. They highlight three dimensions—consumption, capital, and location—showing how unequal endowments shape housing outcomes and how neighbourhood “memberships” propagate disparities. Their analysis emphasises racial discrimination, segregation, and the role of housing in reinforcing wealth and opportunity gaps.','https://pubs.aeaweb.org/doi/pdfplus/10.1257/jel.20251659','10.1257/jel.20251659',NULL,NULL,NULL,'#housing #inequality #jel','2026-05-28 08:52:26');
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('items',15);
COMMIT;
